version: "3"
services:
  netology-db:
      image: postgres:14.5
      container_name: SokolovAV-netology-db
      ports: 
        - 5432:5432
      volumes: 
        - ./pgdata:/var/lib/postgresql/data/pgdata
      environment:
        POSTGRES_PASSWORD: SokolovAV12!3!!
        POSTGRES_DB: SokolovAV-db
        PGDATA: /var/lib/postgresql/data/pgdata
      networks:
        SokolovAV-my-netology-hw:
          ipv4_address: 172.22.0.2
      restart: always
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - netology-db
    container_name: SokolovAV-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: SokolovAV@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 321
    ports:
      - 61231:80
    networks:
      SokolovAV-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always


zabbix-server:
 image: zabbix/zabbix-server-pgsql
 links:
 - netology-db
 container_name: SokolovAV-zabbix-netology
 environment:
    DB_SERVER_HOST: 172.22.0.2
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: SokolovAV12!3!!
 ports:
 - "10051:10051"
 networks:
  SokolovAV-my-netology-hw:
      ipv4_address: 172.22.0.4
  restart: always


zabbix_wgui:
 image: zabbix/zabbix-web-apache-pgsql
 links:
 - netology-db
 - zabbix-server
 container_name: SokolovAV-netology-zabbix-frontend
 environment:
    DB_SERVER_HOST: 172.22.0.2
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: SokolovAV12!3!!
    ZBX_SERVER_HOST: "zabbix_wgui"
    PHP_TZ: "Europe/Moscow"
 ports:
    - "80:8080"
    - "443:8443"
 networks:
 SokolovAV-my-netology-hw:
    ipv4_address: 172.22.0.5
restart: always
  






networks:
  SokolovAV-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24