version: "3"
services:
 netology-db:
  image: postgres:13
  container_name: SokolovAV-netology-db
  ports: -5432:5432
  volumes: ./pgdata:/var/lib/postgresql/data/pgdata
  inviroment:
  POSTGRES_PASSWORD: SokolovAV12!3!!
  POSTGRES_DB: SokolovAV-db
  PGDATA: /var/lib/postgresql/data/pgdata
  
networks:
  SokolovAV-my-netology-hw:
driver: bridge
ipam:
config:
  - subnet: 172.22.0.0/24
    restart: always
