---
- name: "Install packages Tuned"
  hosts: servers
  become: true 
  become_method: sudo
  
  
  tasks:
  
  - name: "Required packages"
    become_method: sudo
    apt:
      name:
        - tuned
        - tuned-utils
        - tuned-utils-systemtap
      state: latest
        
      
      
  - name: "Start tuned"
    systemd:
      name: tuned
      state: started
      enabled: yes
       
...