---
- hosts: "all"
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    moto: Хорошего дня чувак!
  tasks:
    - name: Change /etc/motd
      copy:
        content:
          - "{{ moto }}"
          - "{{ ansible_facts.default_ipv4.address}}"
          - "{{ ansible_facts.hostname}}"
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
  
  